"""Create TIGER tables

Revision ID: 78345c9887ab
Revises: f0236b1cc782
Create Date: 2024-03-18 09:26:52.284145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

from housing.model import SRID

# revision identifiers, used by Alembic.
revision: str = '78345c9887ab'
down_revision: Union[str, None] = 'f0236b1cc782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('states',
                               sa.Column('fips', sa.String(
                                   length=2), nullable=False),
                               sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=SRID, spatial_index=False,
                                         from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
                               sa.PrimaryKeyConstraint('fips'),
                               schema='tiger'
                               )
    op.create_geospatial_index('idx_states_geom', 'states', [
                               'geom'], unique=False, schema='tiger', postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_states_geom', table_name='states',
                             schema='tiger', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('states', schema='tiger')
    # ### end Alembic commands ###
